spring.application.name=discografia
spring.data.mongodb.uri=mongodb+srv://jaimeramirez765_db_user:SVhXIVgU7qnm7G2t@eva-u2-spring.olh03m9.mongodb.net/discografica-db?retryWrites=true&w=majority&appName=eva-u2-spring
spring.data.mongodb.database=discografica-db
server.port=3000
